// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: communication_service.proto

package communicationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationReq) Reset() {
	*x = GetNotificationReq{}
	mi := &file_communication_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationReq) ProtoMessage() {}

func (x *GetNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_communication_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationReq.ProtoReflect.Descriptor instead.
func (*GetNotificationReq) Descriptor() ([]byte, []int) {
	return file_communication_service_proto_rawDescGZIP(), []int{0}
}

type GetNotificationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationRes) Reset() {
	*x = GetNotificationRes{}
	mi := &file_communication_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRes) ProtoMessage() {}

func (x *GetNotificationRes) ProtoReflect() protoreflect.Message {
	mi := &file_communication_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRes.ProtoReflect.Descriptor instead.
func (*GetNotificationRes) Descriptor() ([]byte, []int) {
	return file_communication_service_proto_rawDescGZIP(), []int{1}
}

type MarkNotificationAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNotificationAsReadRequest) Reset() {
	*x = MarkNotificationAsReadRequest{}
	mi := &file_communication_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationAsReadRequest) ProtoMessage() {}

func (x *MarkNotificationAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationAsReadRequest) Descriptor() ([]byte, []int) {
	return file_communication_service_proto_rawDescGZIP(), []int{2}
}

type MarkNotificationAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNotificationAsReadResponse) Reset() {
	*x = MarkNotificationAsReadResponse{}
	mi := &file_communication_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationAsReadResponse) ProtoMessage() {}

func (x *MarkNotificationAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkNotificationAsReadResponse) Descriptor() ([]byte, []int) {
	return file_communication_service_proto_rawDescGZIP(), []int{3}
}

type MarkAllNotificationsAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsAsReadRequest) Reset() {
	*x = MarkAllNotificationsAsReadRequest{}
	mi := &file_communication_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsAsReadRequest) ProtoMessage() {}

func (x *MarkAllNotificationsAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsAsReadRequest) Descriptor() ([]byte, []int) {
	return file_communication_service_proto_rawDescGZIP(), []int{4}
}

type MarkAllNotificationsAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsAsReadResponse) Reset() {
	*x = MarkAllNotificationsAsReadResponse{}
	mi := &file_communication_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsAsReadResponse) ProtoMessage() {}

func (x *MarkAllNotificationsAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsAsReadResponse) Descriptor() ([]byte, []int) {
	return file_communication_service_proto_rawDescGZIP(), []int{5}
}

type AcceptPlayerRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptPlayerRequestRequest) Reset() {
	*x = AcceptPlayerRequestRequest{}
	mi := &file_communication_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptPlayerRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptPlayerRequestRequest) ProtoMessage() {}

func (x *AcceptPlayerRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptPlayerRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptPlayerRequestRequest) Descriptor() ([]byte, []int) {
	return file_communication_service_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptPlayerRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AcceptPlayerRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptPlayerRequestResponse) Reset() {
	*x = AcceptPlayerRequestResponse{}
	mi := &file_communication_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptPlayerRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptPlayerRequestResponse) ProtoMessage() {}

func (x *AcceptPlayerRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptPlayerRequestResponse.ProtoReflect.Descriptor instead.
func (*AcceptPlayerRequestResponse) Descriptor() ([]byte, []int) {
	return file_communication_service_proto_rawDescGZIP(), []int{7}
}

type RejectPlayerRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectPlayerRequestRequest) Reset() {
	*x = RejectPlayerRequestRequest{}
	mi := &file_communication_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectPlayerRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectPlayerRequestRequest) ProtoMessage() {}

func (x *RejectPlayerRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectPlayerRequestRequest.ProtoReflect.Descriptor instead.
func (*RejectPlayerRequestRequest) Descriptor() ([]byte, []int) {
	return file_communication_service_proto_rawDescGZIP(), []int{8}
}

func (x *RejectPlayerRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RejectPlayerRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectPlayerRequestResponse) Reset() {
	*x = RejectPlayerRequestResponse{}
	mi := &file_communication_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectPlayerRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectPlayerRequestResponse) ProtoMessage() {}

func (x *RejectPlayerRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectPlayerRequestResponse.ProtoReflect.Descriptor instead.
func (*RejectPlayerRequestResponse) Descriptor() ([]byte, []int) {
	return file_communication_service_proto_rawDescGZIP(), []int{9}
}

var File_communication_service_proto protoreflect.FileDescriptor

const file_communication_service_proto_rawDesc = "" +
	"\n" +
	"\x1bcommunication_service.proto\x12\rcommunication\"\x14\n" +
	"\x12GetNotificationReq\"\x14\n" +
	"\x12GetNotificationRes\"\x1f\n" +
	"\x1dMarkNotificationAsReadRequest\" \n" +
	"\x1eMarkNotificationAsReadResponse\"#\n" +
	"!MarkAllNotificationsAsReadRequest\"$\n" +
	"\"MarkAllNotificationsAsReadResponse\",\n" +
	"\x1aAcceptPlayerRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1d\n" +
	"\x1bAcceptPlayerRequestResponse\",\n" +
	"\x1aRejectPlayerRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1d\n" +
	"\x1bRejectPlayerRequestResponse2\xc5\x04\n" +
	"\x13NotificationService\x12W\n" +
	"\x0fGetNotification\x12!.communication.GetNotificationReq\x1a!.communication.GetNotificationRes\x12u\n" +
	"\x16MarkNotificationAsRead\x12,.communication.MarkNotificationAsReadRequest\x1a-.communication.MarkNotificationAsReadResponse\x12\x81\x01\n" +
	"\x1aMarkAllNotificationsAsRead\x120.communication.MarkAllNotificationsAsReadRequest\x1a1.communication.MarkAllNotificationsAsReadResponse\x12l\n" +
	"\x13AcceptPlayerRequest\x12).communication.AcceptPlayerRequestRequest\x1a*.communication.AcceptPlayerRequestResponse\x12l\n" +
	"\x13RejectPlayerRequest\x12).communication.RejectPlayerRequestRequest\x1a*.communication.RejectPlayerRequestResponseBIZGgithub.com/Junaidmdv/goalcircle-protos/communication/v1;communicationv1b\x06proto3"

var (
	file_communication_service_proto_rawDescOnce sync.Once
	file_communication_service_proto_rawDescData []byte
)

func file_communication_service_proto_rawDescGZIP() []byte {
	file_communication_service_proto_rawDescOnce.Do(func() {
		file_communication_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_communication_service_proto_rawDesc), len(file_communication_service_proto_rawDesc)))
	})
	return file_communication_service_proto_rawDescData
}

var file_communication_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_communication_service_proto_goTypes = []any{
	(*GetNotificationReq)(nil),                 // 0: communication.GetNotificationReq
	(*GetNotificationRes)(nil),                 // 1: communication.GetNotificationRes
	(*MarkNotificationAsReadRequest)(nil),      // 2: communication.MarkNotificationAsReadRequest
	(*MarkNotificationAsReadResponse)(nil),     // 3: communication.MarkNotificationAsReadResponse
	(*MarkAllNotificationsAsReadRequest)(nil),  // 4: communication.MarkAllNotificationsAsReadRequest
	(*MarkAllNotificationsAsReadResponse)(nil), // 5: communication.MarkAllNotificationsAsReadResponse
	(*AcceptPlayerRequestRequest)(nil),         // 6: communication.AcceptPlayerRequestRequest
	(*AcceptPlayerRequestResponse)(nil),        // 7: communication.AcceptPlayerRequestResponse
	(*RejectPlayerRequestRequest)(nil),         // 8: communication.RejectPlayerRequestRequest
	(*RejectPlayerRequestResponse)(nil),        // 9: communication.RejectPlayerRequestResponse
}
var file_communication_service_proto_depIdxs = []int32{
	0, // 0: communication.NotificationService.GetNotification:input_type -> communication.GetNotificationReq
	2, // 1: communication.NotificationService.MarkNotificationAsRead:input_type -> communication.MarkNotificationAsReadRequest
	4, // 2: communication.NotificationService.MarkAllNotificationsAsRead:input_type -> communication.MarkAllNotificationsAsReadRequest
	6, // 3: communication.NotificationService.AcceptPlayerRequest:input_type -> communication.AcceptPlayerRequestRequest
	8, // 4: communication.NotificationService.RejectPlayerRequest:input_type -> communication.RejectPlayerRequestRequest
	1, // 5: communication.NotificationService.GetNotification:output_type -> communication.GetNotificationRes
	3, // 6: communication.NotificationService.MarkNotificationAsRead:output_type -> communication.MarkNotificationAsReadResponse
	5, // 7: communication.NotificationService.MarkAllNotificationsAsRead:output_type -> communication.MarkAllNotificationsAsReadResponse
	7, // 8: communication.NotificationService.AcceptPlayerRequest:output_type -> communication.AcceptPlayerRequestResponse
	9, // 9: communication.NotificationService.RejectPlayerRequest:output_type -> communication.RejectPlayerRequestResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_communication_service_proto_init() }
func file_communication_service_proto_init() {
	if File_communication_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_communication_service_proto_rawDesc), len(file_communication_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communication_service_proto_goTypes,
		DependencyIndexes: file_communication_service_proto_depIdxs,
		MessageInfos:      file_communication_service_proto_msgTypes,
	}.Build()
	File_communication_service_proto = out.File
	file_communication_service_proto_goTypes = nil
	file_communication_service_proto_depIdxs = nil
}
