syntax ='proto3'; 

package communication; 

option go_package = "github.com/Junaidmdv/goalcircle-protos/communication/v1;communicationv1";  
import "google/protobuf/struct.proto";



message GetNotificationsReq{ 
  string user_id=1;
} 

// enum NotificationType {
//   NOTIFICATION_TYPE_UNSPECIFIED = 0;
//   NOTIFICATION_TYPE_TEAM_INVITATION = 1;
//   NOTIFICATION_TYPE_REQUEST_ACCEPTED = 2;
//   NOTIFICATION_TYPE_REQUEST_REJECTED = 3;
// }


message GetNotificationsRes{ 
    message NotificationDetail{
       string notification_id=1;  
       string notification_type = 2; 
       string title=3; 
       string message=4;
       google.protobuf.Struct data = 5;
    } 
    
    string user_id=1;
    repeated NotificationDetail notification_detail = 2;

}  

message MarkNotificationAsReadRequest{
    string user_id=1; 
    string notification_id=2;
} 

message MarkNotificationAsReadResponse{
   bool success=1;
}  

message MarkAllNotificationsAsReadRequest{
    string user_id=1;
}


message MarkAllNotificationsAsReadResponse{
   int64 update_count=1;
}

message AcceptPlayerRequestRequest {
  string id = 1;
}

message AcceptPlayerRequestResponse {
}

message RejectPlayerRequestRequest {
  string id = 1;
}

message RejectPlayerRequestResponse {
}


service NotificationService { 
    rpc GetNotifications(GetNotificationsReq)returns(GetNotificationsRes); 
    rpc MarkNotificationAsRead(MarkNotificationAsReadRequest) returns (MarkNotificationAsReadResponse);
    rpc MarkAllNotificationsAsRead(MarkAllNotificationsAsReadRequest) returns (MarkAllNotificationsAsReadResponse);
    rpc AcceptPlayerRequest(AcceptPlayerRequestRequest) returns (AcceptPlayerRequestResponse);
    rpc RejectPlayerRequest(RejectPlayerRequestRequest) returns (RejectPlayerRequestResponse);
}