syntax ='proto3'; 

package team; 

option go_package = "github.com/Junaidmdv/goalcircle-protos/user/v1;teamv1";  

import "google/protobuf/timestamp.proto";


message TeamOwnerDetails{
    string user_id=1;    
    string full_name=2; 
}




message CreateTeamReq{
    string name=1; 
    string city=2; 
    string description = 3; 
    string refresh_token=4;   
    string contact_num=5;  
    string email=6;
    TeamOwnerDetails owner=8;
}



message UserRes{
   string session_id=1; 
   string user_id=2;  
   string email=3;  
   string access_token=4;  
   google.protobuf.Timestamp access_token_expiry=5; 
   string refresh_token=6; 
   google.protobuf.Timestamp refresh_token_expiry=7;
} 

message TeamDetailsRes{
  string id=1;  
  string name=2; 
  string short_name=3;  
  string city=4; 
  string team_code=5;
} 

message TeamMemberDetails{
  string team_member_id=1; 
  string full_name=2;
  string role=3;
}


message CreateTeamRes{   
  UserRes user=1;  
  TeamDetailsRes team_details=2; 
  TeamMemberDetails team_member=3;

} 


message UpdateTeamReq{   
  string user_id=1;
  optional string name=2; 
  optional string city=3; 
  optional string description = 4; 
  optional string short_name=5; 
  optional string email=6;  
  optional string phone_number=7;
}


message UpdateTeamRes{  
  string team_id=1; 
  string name=2; 
  string city=3; 
  string description = 4; 
  string short_name=5;
}


message RegisterTeamMemberReq{
   
} 

message RegisterTeamMemberRes{

}


// message UpdateTeamContactDetailsReq{  
//     string contact_email=1; 
//     string contact_phone_num=2;
//     string team_id=3; 
//     string team_member_id=4;
// }

// message UpdateTeamContactDetailsRes{
//   string team_id=1; 
//   string contact_email=2; 
//   string contact_phone_num=3; 
// }

message SetCaptainRes{ 
  string player_id=2;
} 

message SetCaptainReq{
   string user_id=1; 
   string team_id=2; 
   string player_id=3; 
}

message SetViceCaptainRes{
   string player_id=1;
}

message SetViceCaptainReq{
   string user_id=1; 
   string team_id=2; 
   string player_id=3;
}  


enum TeamStatus {
  TEAM_STATUS_UNSPECIFIED = 0;
  TEAM_STATUS_ACTIVE = 1;
  TEAM_STATUS_INACTIVE = 2;
  TEAM_STATUS_SUSPENDED = 3;
  TEAM_STATUS_ARCHIVED = 4;
}


message ListTeamReq{
   int32  page=1; 
   int32 limit=2; 
   string city=3;
   TeamStatus team_status=4;
   string search=5;
}


message TeamDetails{
   string team_id=1; 
   string name=2;  
   string city=3;  
   string logo_url=4;  
   string team_code=5;  
   TeamStatus team_status=6;
} 


message  PaginateTeam {
   int32 total_page=1; 
   int32 page=2; 
   int32 limit=3;  
   int64 total_item=4;
}



message ListTeamRes{
  repeated TeamDetails team_details = 1; 
  PaginateTeam pagination=2;
}


message GetTeamReq{
   string team_id=1; 
}  



message GetTeamRes{
   string team_id=1; 
   string name=2;  
   string short_name=3;  
   string city=4;  
   string logo_key=5;  
   string team_code=6;  
   string email=7; 
   string phone_num=8; 
   string team_status=9;  
   int32  player_count=10; 
   string caption_id=11;  
   string vice_caption_id=12;
}

message TeamLogoMetaData{ 
   string user_id=1;
   string content_type=2; 
}


message AddLogoReq{
   oneof data {
     TeamLogoMetaData  meta_data=1; 
      bytes chunk=2;
   }
}

message AddLogoRes{   
   string team_id=1;
   string resigned_url=2; 
}


// message RemoveLgoReq{
//    string team_id=1; 
//    string user_id=2;
// }

// message RemoveLogoRes{
//    string team_id=1; 
// }




message GetPresignedUrlReq{
    string team_id=1;
}

message GetPresignedUrlRes{
   string team_id=1; 
   string presigned_url=2;
}





service TeamService {
   rpc CreateTeam(CreateTeamReq)returns (CreateTeamRes); 
   rpc UpdateTeam(UpdateTeamReq)returns(UpdateTeamRes);  
   rpc RegisterTeamMember(RegisterTeamMemberReq)returns(RegisterTeamMemberRes);  
   rpc SetCaptain(SetCaptainReq)returns(SetCaptainRes); 
   rpc SetViceCaptain(SetViceCaptainReq)returns(SetViceCaptainRes); 
   rpc ListTeam(ListTeamReq)returns(ListTeamRes); 
   rpc GetTeam(GetTeamReq)returns(GetTeamRes); 
   rpc AddLogo(stream AddLogoReq)returns(AddLogoRes); 
   // rpc RemoveLogo(RemoveLgoReq)returns(RemoveLogoRes); 
   rpc GetLogoPresignedUrl(GetPresignedUrlReq)returns(GetPresignedUrlRes);
}



message PlayerDetails{
string full_name=1; 
 google.protobuf.Timestamp date_of_birth=2;  
 int32 jersey_number=3;  
 int32 position=4;  
 float height=5;
 float weight=6;   
 string team_id=7; 
 string user_id=8;
}



message AddPlayerReq{  
   oneof player{
      PlayerDetails player_details=1; 
      bytes player_image_chunks=2;
   }
} 

message AddPlayerRes{ 
  string player_id=1; 
  string team_member_id=2; 
  string full_name=3; 
  int32 jersey_number=4; 
  string player_position = 5; 
  string player_status =6; 
 string presigned_url=7;
}

message UpdatePlayerRequest {
  string user_id = 1;
  string team_id = 2;
  string player_id = 3;

  optional string full_name = 4;
  optional google.protobuf.Timestamp date_of_birth = 5;
  optional int32 jersey_number = 6;
  optional PlayerPosition position = 7;
  optional float height = 8;
  optional float weight = 9;
  optional PlayerStatus status = 10;
}

message UpdatePlayersResponse {
  string player_id = 1;
  string team_member_id = 2;
  string full_name = 3;
  google.protobuf.Timestamp date_of_birth = 4;
  int32 jersey_number = 5;
  PlayerPosition position = 6;
  float height = 7;
  float weight = 8;
  PlayerStatus status = 9;
}


message UpdatePlayerStatusRes{
   string player_id=1; 
   string player_status=2; 
} 

enum  PlayerStatus {
  STATUS_UNSPECIFIED = 0; 
  STATUS_ACTIVE=1; 
  STATUS_INACTIVE=2; 
  STATUS_SUSPENDED=3; 
  STATUS_RELEASED=4;
}

enum PlayerPosition {
  PLAYER_POSITION_UNSPECIFIED = 0;

  PLAYER_POSITION_GK  = 1;

  PLAYER_POSITION_CB  = 2;
  PLAYER_POSITION_LB  = 3;
  PLAYER_POSITION_RB  = 4;
  PLAYER_POSITION_LWB = 5;
  PLAYER_POSITION_RWB = 6;

  PLAYER_POSITION_CDM = 7;
  PLAYER_POSITION_CM  = 8;
  PLAYER_POSITION_CAM = 9;
  PLAYER_POSITION_LM  = 10;
  PLAYER_POSITION_RM  = 11;

  PLAYER_POSITION_LW  = 12;
  PLAYER_POSITION_RW  = 13;
  PLAYER_POSITION_CF  = 14;
  PLAYER_POSITION_ST  = 15;
}

message ListTeamPlayerReq{
   string team_id=1; 
   int32  page=2; 
   int32 limit=3; 
   optional PlayerPosition position=4;   
   optional PlayerStatus player_status=5;
   optional  string search=6;
}


message PlayerList{
   string player_id=1;
   string team_member_id=2;
   string full_name=3;
   int32 jersey_number=4; 
   PlayerPosition position=5;
}

message PaginationDetails{
    int32 total_page=1; 
    int32 page=2; 
    int32 limit=3;  
    int64 total_item=4;
}


message ListTeamPlayerRes{ 
   PaginationDetails paginate=1;
   repeated PlayerList players=2;
}

message GetPlayerReq{
   string player_id=1;  
   string team_id=2;
}


message  GetPlayerRes {
  string player_id=1; 
  string team_member_id=2;
  string full_name=3; 
  google.protobuf.Timestamp dob=4; 
  int32 jersey_number=5; 
  PlayerPosition player_position = 6; 
  float height=7;
  float weight=8;  
  PlayerStatus player_status = 9; 
  google.protobuf.Timestamp created_at = 10;
}


message ReleasePlayerReq{
    string player_id=1; 
    string team_id=2; 
    string user_id=3; 
}


message ReleasePlayerRes{
   bool success=1;  
}


message UpdatePlayerImageMeta{
    string team_id=1; 
    string player_id=2;
    string user_id=3;

}

message UpdatePlayerImageReq{
     oneof data {
         UpdatePlayerImageMeta meta=1; 
         bytes chunks=2;
     }
}

message UpdatePlayerImageRes{
   string team_id=1; 
   string player_id=2; 
   string presigned_url=3; 
}


message GetPlayerPresignedUrlReq{
     string team_id=1; 
     string player_id=2;
     string user_id=3;
}

message GetPlayerPresignedUrlRes{
     string team_id=1; 
     string player_id=2; 
     string presigned_url=3; 
}

message RemovePlayerImageReq{ 
     string  team_id=1; 
     string  user_id=2; 
     string player_id=3;
}

message RemovePlayerImageRes{
    bool success=1;
}

service PlayerService{
  rpc AddNewPlayer(stream AddPlayerReq)returns(AddPlayerRes); 
  rpc UpdatePlayerDetails(UpdatePlayerRequest)returns(UpdatePlayersResponse); 
  rpc ListTeamPlayer(ListTeamPlayerReq)returns(ListTeamPlayerRes);  
  rpc GetPlayer(GetPlayerReq)returns(GetPlayerRes);  
  rpc ReleasePlayer(ReleasePlayerReq)returns(ReleasePlayerRes);  
  rpc UpdatePlayerImage(stream UpdatePlayerImageReq)returns(UpdatePlayerImageRes); 
  rpc GetPlayerPresignedUrl(GetPlayerPresignedUrlReq)returns(GetPlayerPresignedUrlRes);  
  rpc RemovePlayerImage(RemovePlayerImageReq)returns(RemovePlayerImageRes);

}



message CreateInvitationReq{
   string team_member_id=1; 
   string user_id=2;
  } 

message CreateInvitationRes{
  string code=1; 
  google.protobuf.Timestamp created_at = 2; 
  google.protobuf.Timestamp expired_at=3; 
}



service   TeamInvite {
    rpc CreateInvitation(CreateInvitationReq)returns(CreateInvitationRes); 
}


enum StaffDesignation {
  STAFF_DESIGNATION_UNSPECIFIED = 0;

  STAFF_DESIGNATION_OWNER = 1;
  STAFF_DESIGNATION_MANAGER = 2;

  STAFF_DESIGNATION_HEAD_COACH = 3;
  STAFF_DESIGNATION_ASSISTANT_COACH = 4;
  STAFF_DESIGNATION_GOALKEEPER_COACH = 5;
  STAFF_DESIGNATION_FITNESS_COACH = 6;

  STAFF_DESIGNATION_PHYSIO = 7;
  STAFF_DESIGNATION_DOCTOR = 8;

  STAFF_DESIGNATION_ANALYST = 9;
  STAFF_DESIGNATION_OTHER = 10;
}

enum StaffRole {
  STAFF_ROLE_UNSPECIFIED = 0;
  STAFF_ROLE_MANAGEMENT = 1;
  STAFF_ROLE_COACH = 2;
  STAFF_ROLE_MEDICAL = 3;
  STAFF_ROLE_OTHER = 4;
}



message StaffDetails{
  string team_id=1;  
  string user_id=2;
  string full_name=3;  
  StaffRole role=4;
  StaffDesignation designation=5; 
  optional string specialised=6;
  google.protobuf.Timestamp dob=7; 
}


message AddStaffReq{  
    oneof data {
         StaffDetails meta=1; 
         bytes chunks=2;
     }
}

message AddStaffRes{
  string staff_id=1; 
  string team_member_id=2; 
  string full_name=3; 
  int32 age=4; 
  string designatin=5;  
  string role=6;
} 

message StaffImageMeta{
   string team_id=1; 
   string staff_id=2; 
   string  user_id=3;
}

message UpdateStaffImageReq{  
 oneof data {
         StaffImageMeta meta=1; 
         bytes chunks=2;
     }

} 

message UpdateStaffImageRes{
    string staff_id=1; 
    string presigned_url=2; 
}  

message GetStaffImageUrlReq{
  string staff_id=1;
}

message GetStaffImageUrlRes{
   string staff_id=1; 
   string presigned_url=2;
}


message RemoveStaffImageReq{
    string user_id=1; 
    string team_id=2; 
    string staff_id=3;
} 

message RemoveStaffImageRes{
   bool success=1;
}

message UpdateStaffReq{
 string user_id=1; 
  string team_id=2;  
  string staff_id=3; 
  optional string full_name=4; 
  optional google.protobuf.Timestamp dob=5;
  optional StaffRole role=6; 
  optional StaffDesignation designation=7; 
  optional string phone_num=8;
}

message UpdateStaffRes{
  string staff_id = 1;
  string team_member_id = 2;
  string full_name = 3;
  google.protobuf.Timestamp date_of_birth = 4;
  int32 age = 5;
  string role = 6;
  string designation = 7;
  string phone_num = 8;
  google.protobuf.Timestamp created_at = 9;
  google.protobuf.Timestamp updated_at = 10;
} 

message GetStaffReq{
   string staff_id=1; 
   string team_id=2; 
} 

message GetStaffRes{
  string id = 1;
  string team_member_id = 2;
  string full_name = 3;
  string date_of_birth = 4;
  string role = 5;
  string designation = 6;
  string phone_num = 7;
  google.protobuf.Timestamp created_at = 8;
  string status = 9;
  string joined_at = 10;
  optional string released_at = 11;
  optional string resigned_at = 12;
}
 
message ListTeamStaffReq{
 string team_id=1; 
 int32   page=2; 
 int32   limit=3; 
 StaffRole   role=4; 
 StaffDesignation   designation=5; 
 string   search=6;
}

message StaffDetailResponse{ 
   string staff_id=1; 
   string team_member_id=2;
   string full_name=3;  
   string role=4; 
   string designation=5; 
   string presigned_url=6; 
   google.protobuf.Timestamp released_at=7; 
   google.protobuf.Timestamp joined_at=8; 
   string status=9;
} 

message StaffPaginationDetails{
  int32 total_page=1;  
  int32 page=2;  
  int32 limit=3; 
  int64 total=4;
}


message ListTeamStaffRes{
  repeated StaffDetailResponse staff_detail = 1; 
  StaffPaginationDetails pagination=2;
} 

message ReleaseStaffReq{
  string user_id=1; 
  string staff_id=2; 
  string  team_id=3;
} 

message ReleaseStaffRes{
  string staff_id = 1;
  string team_member_id = 2;
  string full_name = 3;
  string role = 4;
  string designation = 5;
  string status = 6;
  string joined_at = 7;
  string released_at = 8;
}

message TransferOwnershipReq{

} 

message TransferOwnershipRes{

}


service StaffService {
     rpc AddStaff(stream AddStaffReq)returns(AddStaffRes); 
     rpc GetStaff(GetStaffReq)returns(GetStaffRes);
     rpc UpdateStaffImage(stream UpdateStaffImageReq)returns(UpdateStaffImageRes); 
     rpc GetStaffImageUrl(GetStaffImageUrlReq)returns(GetStaffImageUrlRes); 
     rpc RemoveStaffImage(RemoveStaffImageReq)returns(RemoveStaffImageRes);  
     rpc UpdateStaff(UpdateStaffReq)returns(UpdateStaffRes);  
     rpc ListTeamStaff(ListTeamStaffReq)returns(ListTeamStaffRes); 
     rpc ReleaseStaff(ReleaseStaffRes)returns(ReleaseStaffRes); 
     rpc TransferOwnership(TransferOwnershipReq)returns(TransferOwnershipRes);

}