// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: team_service.proto

package teamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTeamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamReq) Reset() {
	*x = CreateTeamReq{}
	mi := &file_team_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamReq) ProtoMessage() {}

func (x *CreateTeamReq) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamReq.ProtoReflect.Descriptor instead.
func (*CreateTeamReq) Descriptor() ([]byte, []int) {
	return file_team_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTeamReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeamReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateTeamReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTeamReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTeamReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type CreateTeamRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamCode      string                 `protobuf:"bytes,2,opt,name=team_code,json=teamCode,proto3" json:"team_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRes) Reset() {
	*x = CreateTeamRes{}
	mi := &file_team_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRes) ProtoMessage() {}

func (x *CreateTeamRes) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRes.ProtoReflect.Descriptor instead.
func (*CreateTeamRes) Descriptor() ([]byte, []int) {
	return file_team_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTeamRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTeamRes) GetTeamCode() string {
	if x != nil {
		return x.TeamCode
	}
	return ""
}

type UpdateTeamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamReq) Reset() {
	*x = UpdateTeamReq{}
	mi := &file_team_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamReq) ProtoMessage() {}

func (x *UpdateTeamReq) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamReq.ProtoReflect.Descriptor instead.
func (*UpdateTeamReq) Descriptor() ([]byte, []int) {
	return file_team_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTeamReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *UpdateTeamReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTeamReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateTeamReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateTeamRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamRes) Reset() {
	*x = UpdateTeamRes{}
	mi := &file_team_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamRes) ProtoMessage() {}

func (x *UpdateTeamRes) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamRes.ProtoReflect.Descriptor instead.
func (*UpdateTeamRes) Descriptor() ([]byte, []int) {
	return file_team_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTeamRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_team_service_proto protoreflect.FileDescriptor

const file_team_service_proto_rawDesc = "" +
	"\n" +
	"\x12team_service.proto\x12\x04team\"\x97\x01\n" +
	"\rCreateTeamReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\tR\frefreshToken\"E\n" +
	"\rCreateTeamRes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tteam_code\x18\x02 \x01(\tR\bteamCode\"r\n" +
	"\rUpdateTeamReq\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\")\n" +
	"\rUpdateTeamRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2}\n" +
	"\vTeamService\x126\n" +
	"\n" +
	"CreateTeam\x12\x13.team.CreateTeamReq\x1a\x13.team.CreateTeamRes\x126\n" +
	"\n" +
	"UpdateTeam\x12\x13.team.UpdateTeamReq\x1a\x13.team.UpdateTeamResB7Z5github.com/Junaidmdv/goalcircle-protos/user/v1;teamv1b\x06proto3"

var (
	file_team_service_proto_rawDescOnce sync.Once
	file_team_service_proto_rawDescData []byte
)

func file_team_service_proto_rawDescGZIP() []byte {
	file_team_service_proto_rawDescOnce.Do(func() {
		file_team_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_team_service_proto_rawDesc), len(file_team_service_proto_rawDesc)))
	})
	return file_team_service_proto_rawDescData
}

var file_team_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_team_service_proto_goTypes = []any{
	(*CreateTeamReq)(nil), // 0: team.CreateTeamReq
	(*CreateTeamRes)(nil), // 1: team.CreateTeamRes
	(*UpdateTeamReq)(nil), // 2: team.UpdateTeamReq
	(*UpdateTeamRes)(nil), // 3: team.UpdateTeamRes
}
var file_team_service_proto_depIdxs = []int32{
	0, // 0: team.TeamService.CreateTeam:input_type -> team.CreateTeamReq
	2, // 1: team.TeamService.UpdateTeam:input_type -> team.UpdateTeamReq
	1, // 2: team.TeamService.CreateTeam:output_type -> team.CreateTeamRes
	3, // 3: team.TeamService.UpdateTeam:output_type -> team.UpdateTeamRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_team_service_proto_init() }
func file_team_service_proto_init() {
	if File_team_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_team_service_proto_rawDesc), len(file_team_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_team_service_proto_goTypes,
		DependencyIndexes: file_team_service_proto_depIdxs,
		MessageInfos:      file_team_service_proto_msgTypes,
	}.Build()
	File_team_service_proto = out.File
	file_team_service_proto_goTypes = nil
	file_team_service_proto_depIdxs = nil
}
